# Generated by Django 4.2.16 on 2026-05-13 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='AreaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outbound.area')),
            ],
            options={
                'db_table': 'area_categorias',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_ingreso',
            },
        ),
        migrations.CreateModel(
            name='TipoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_salida',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'unidades_medida',
            },
        ),
        migrations.CreateModel(
            name='SalidaProducto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nro_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_salida', models.DateTimeField()),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outbound.sucursal')),
            ],
            options={
                'db_table': 'salidas_productos',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_actual', models.CharField(max_length=50, unique=True)),
                ('codigo_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_corta', models.CharField(max_length=255)),
                ('especificacion_tecnica', models.TextField(blank=True, null=True)),
                ('costo_cliente_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('costo_clinica_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('costo_licitacion_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stock_minimo_global', models.IntegerField(default=5)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=10)),
                ('area_categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outbound.areacategoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outbound.marca')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outbound.unidadmedida')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='EntradaProducto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nro_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_entrada', models.DateTimeField()),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outbound.sucursal')),
            ],
            options={
                'db_table': 'entradas_productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outbound.area')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outbound.item')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outbound.tiposalida')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outbound.salidaproducto')),
            ],
            options={
                'db_table': 'detalle_salidas',
            },
        ),
        migrations.CreateModel(
            name='DetalleEntrada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outbound.area')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outbound.entradaproducto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outbound.item')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outbound.tipoingreso')),
            ],
            options={
                'db_table': 'detalle_entradas',
            },
        ),
        migrations.AddField(
            model_name='areacategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outbound.categoria'),
        ),
        migrations.CreateModel(
            name='StockSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_saldo', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outbound.item')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='outbound.sucursal')),
            ],
            options={
                'db_table': 'stock_sucursales',
                'unique_together': {('item', 'sucursal')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='areacategoria',
            unique_together={('area', 'categoria')},
        ),
    ]
