# Generated by Django 4.2.16 on 2026-05-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
