# Generated by Django 4.2.16 on 2026-05-16 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('vendedor_id', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('sucursal', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, to='outbound.sucursal')),
            ],
            options={
                'db_table': 'proformas',
            },
        ),
        migrations.CreateModel(
            name='DetalleProforma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, to='outbound.area')),
                ('item', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.RESTRICT, to='outbound.item')),
                ('proforma', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='outbound.proforma')),
            ],
            options={
                'db_table': 'detalle_proformas',
            },
        ),
    ]
